name: sakcamera_getx
description: "The SAK Camera application is a system for capturing timestamped photos for internal organizational use. It allows taking and saving photos with additional elements such as the organization’s logo, location information, and a map included in the image. These photos can then be used within the organization, for example as supporting materials in internal documents, providing information that is fast, convenient, and complete."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Setting
  flutter_inappwebview: ^6.1.5 #not support  Linux. #setting //===>> (web ใน app)
  url_launcher: ^6.2.4 #support all # setting. //===>> (เช็คเวอร์ชัน)
  permission_handler: ^12.0.1 # not support Linux, Macos. # setting. //===>> (การขออนุญาตสิทธิ์การเข้าถึง)
 
  # Camera
  camera: ^0.11.3 # not support Linux, Windows, Macos. # setting. //===>> (กล้อง)
  sensors_plus: ^7.0.0 # not support Linux, Windows, Macos. //===>> จัดการเซ็นเซอร์การหมุน

  # Map
  google_maps_flutter: ^2.14.0 # not support Linux, Windows, Macos //===>> จัดการแผนที่
  geolocator: ^14.0.2
  flutter_map: ^8.2.2

  # Gallery
  carousel_slider: ^5.1.1 # support all  //===>> รูปแบบสไลด์รูปหน้า fullscreen

  # No setting
  get: ^4.7.2 #support all //===>> (GetX State Management)
  device_info_plus: ^11.4.0 # support all # setting. //===>> (ตรวจสอบระบบปฎิบัติการของอุปกรณ์, แพลตฟอร์มและเวอร์ชัน)
  animations: ^2.1.0 # support all. //===>> (เปลี่ยนหน้าให้ smooth ขึ้น)
  loading_animation_widget: ^1.3.0 # support all. //===>> (เปลี่ยนเอฟเฟ็ก Loading)
  flutter_form_builder: ^10.2.0 #support all //===>> (ช่วยจัดการออกแบบ form)
  form_builder_validators: ^11.2.0 #support all //===>> (ช่วยจัดการออกแบบ validation)
  package_rename: ^1.10.0 #not support Web. //===>> (เปลี่ยน ชื่อแอป (App name), เปลี่ยน แพ็กเกจ Android (applicationId),เปลี่ยน Bundle Identifier ของ iOS),เปลี่ยนได้ทั้ง Android/iOS พร้อมกันในคำสั่งเดียว)
  internet_connection_checker_plus: ^2.9.0 #support all. //===>> (ตรวจสอบสถานะการเชื่อมต่ออินเทอร์เน็ตของอุปกรณ์ (ตรวจว่ามีเน็ตจริง))
  another_flushbar: ^1.12.32 #support all. //===>> (ออกแบบ flushvbar ใช้แทน snackbar ได้)
  lottie: ^3.3.2 #support all. //===>> (จัดการ icon json)
  convex_bottom_bar: ^3.2.0 #support all. //===>> (จัดการ เมนู bar)
  photo_manager: ^3.7.1 #not support Linux, Windows, Web //===>> (จัดการการบันทึกไฟล์ลงเครื่อง Android เก่า)
  photo_manager_image_provider: ^2.2.0
  gal: ^2.3.2 #not support Linux, Web //===>> (จัดการการบันทึกไฟล์ลงเครื่อใหม่สำหรับ Android และ iOS)
  path_provider: ^2.1.5 #not support Web //===>> (จัดการ path)
  image: ^4.5.4 #support all //===>> (จัดการ image)
  exif: ^3.3.0
  flutter_image_compress: ^2.1.0 #not support Linux, Windows //===>> (จัดการ format รูปภาพ)
  image_gallery_saver_plus: ^4.0.1


  # Database
  path: ^1.9.1 # support all. //===>> (สร้างที่่เก็บไฟล์และกำหนด path)
  jaguar_jwt: ^3.0.0 # support all. //===>> (จัดการเกี่ยวกับการเข้ารหัสและถอดรหัส)
  shared_preferences: ^2.5.3 #support all. //===>> (เก็บข้อมูลขนาดเล็กแบบถาวร (Key-Value Storage) บนอุปกรณ์)
  sqflite: ^2.4.2 # support all. //===>> (จัดการฐานข้อมูล SQLite ภายในเครื่อง)
  intl: ^0.20.2 # support all. //===>> (แปลงวันที่และเวลาสำหรับภาษาไทย)
  firebase_core: ^4.2.1
  # Database

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  # flutter_launcher_icons: ^0.14.4 #not support Web. //===>> (icon หน้า App)
  # package_rename: ^1.10.0 #not support Web. //===>> (เปลี่ยน ชื่อแอป (App name), เปลี่ยน แพ็กเกจ Android (applicationId),เปลี่ยน Bundle Identifier ของ iOS),เปลี่ยนได้ทั้ง Android/iOS พร้อมกันในคำสั่งเดียว)
  # flutter_native_splash: ^2.2.16 #not support Linux, Macos, Windows. //===>> (หน้าแรกเข้า app)
  device_preview_plus: ^2.5.1

package_rename_config:
  android:
    app_name: SAK Camera
    package_name: com.saksiaml
    override_old_package: com.saksiamleasing.sakcamera
    lang: kotlin
  ios:
    app_name: SAK Camera
    bundle_name: com.saksiamleasing.sakcamera
    package_name: com.saksiamleasing.sakcamera
  linux:
    app_name: SAK Camera
    package_name: com.saksiamleasing.sakcamera
    exe_name: SAK_Camera_Linux
  macos:
    app_name: SAK Camera
    package_name: com.saksiamleasing.sakcamera
    copyright_notice: Saksiam Leasing Public Company Limited
  web:
    app_name: SAK Camera
    short_app_name: SAK Camera
    description: com.saksiamleasing.sakcamera
  windows:
    app_name: SAK Camera
    organization: Saksiam Leasing Public Company Limited
    copyright_notice: Saksiam Leasing Public Company Limited
    exe_name: SAK_Camera_Windows

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/icons/sakcamera_icon_app.png"
  image_path_ios: "assets/icons/sakcamera_icon_ios_app.png"

flutter_native_splash:
  color: "#243865"
  image: assets/images/sakcamera_logo_splashscreen.png
  android: true
  ios: true
  web: true

  android_12:
    image: assets/images/sakcamera_logo_splashscreen.png
    color: "#243865"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/logo/
    - assets/images/
    - assets/lottie/
    - assets/fonts/bitmap-kanit.zip
    - assets/fonts/bitmap-kanit.fnt
    - assets/fonts/bitmap-kanit_0.png

  fonts:
    - family: Sukhumvit
      fonts:
        - asset: assets/fonts/sukhumvit/SukhumvitTadmai-UltraLight.otf
          weight: 200
        - asset: assets/fonts/sukhumvit/SukhumvitTadmai-Text.otf
          weight: 400
        - asset: assets/fonts/sukhumvit/SukhumvitTadmai-SemiBold.otf
          weight: 600
        - asset: assets/fonts/sukhumvit/SukhumvitTadmai-ExtraBold.otf
          weight: 800

    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-Regular.ttf